#!/bin/sh

user=$1
pages=$2

if [ -z $pages ]; then 
	pages=1
fi 

echo "" > /tmp/$user.sold

for page in `seq 1 $pages`; 
do 
	wget -q -O '-' "http://feedback.ebay.fr/ws/eBayISAPI.dll?ViewFeedback2&ftab=AllFeedback&userid=$user&iid=-1&de=off&items=25&interval=0&mPg=272&page=$page" |\
	grep -o '#[0-9]\{7,\}' >> /tmp/$user.sold; 
	echo "Fetching $user page #$page/$pages ..."
done;

echo 'Computing top 10'
cat /tmp/$user.sold | sort | uniq -c | sort -k2nr | awk '{printf("%5s http://cgi.ebay.fr/ws/eBayISAPI.dll?ViewItem&item=%s \n",$1,$2)}END{print}' | sort -n | tr -d '#' | tail -n 10
